// app/components/Contact.vue
<template>
  <div class="font-mono">
    <h1 class="text-2xl font-bold mb-2">Contact</h1>
    <p class="text-terminal-dim mb-2">
      You can reach me at the following email address:
    </p>
    <a
      href="mailto:tanner@teamhydra.dev"
      class="text-terminal-dim hover:text-terminal hover:underline transition-colors"
    >
      tanner@teamhydra.dev
    </a>
    <br />
    <span class="text-terminal-dim">-- or --</span>
    <br />
    <a
      href="https://discord.gg/zira"
      target="_blank"
      class="text-terminal-dim hover:text-terminal hover:underline transition-colors"
    >
      Via Discord
    </a>
    <p class="text-terminal-dim mt-2">
      Please use the #other-support channel to get in touch with me. My
      username is sticksdev.
    </p>
    <p class="text-terminal-dim mt-2">
      I look forward to hearing from you soon :)
    </p>
  </div>
</template>

<script setup lang="ts">
</script>

// src/components/Contact.tsx
export function Contact() {
    return (
        <div>
            <h1 className='text-2xl font-bold font-mono'>Contact</h1>
            <p className='text-gray-500'>
                You can reach me at the following email address:
            </p>
            <a
                href='mailto:tanner@teamhydra.dev'
                className='text-blue-500 hover:underline'
            >
                tanner@teamhydra.dev
            </a>
            <br />
            -- or --
            <br />
            <a
                href='https://discord.gg/zira'
                className='text-blue-500 hover:underline'
            >
                Via Discord
            </a>
            <p className='text-gray-500'>
                Please use the #other-support channel to get in touch with me. My 
                username is sticksdev.
            </p>
            <p className='text-gray-500'>
                I look forward to hearing from you soon :)
            </p>
        </div>
    );
}
